sass:
  sass_dir: _sass
paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jemoji
  - jekyll-paginate
